chance: 50

menu:
  bet1:
    bet: 1000
    slot: 11
    material: EMERALD
    name: "&eApostar R$ 1000"
    lore:
      - "&7Ganhe 2x o valor apostado"
  bet2:
    bet: 5000
    slot: 12
    material: EMERALD
    data: 0
    name: "&eApostar R$ 5000"
    lore:
      - "&7Ganhe 2x o valor apostado"
  bet3:
    bet: 10000
    slot: 13
    material: EMERALD
    data: 0
    name: "&eApostar R$ 10000"
    lore:
      - "&7Ganhe 2x o valor apostado"
  bet4:
    bet: 20000
    slot: 14
    material: EMERALD
    data: 0
    name: "&eApostar R$ 20000"
    lore:
      - "&7Ganhe 2x o valor apostado"
  bet5:
    bet: 0
    slot: 24
    material: REDSTONE
    data: 0
    name: "&eFechar Menu"
    lore:
      - "&7Clique para fechar o menu."
